### ISSUE TITLE
Allow additional (modulating) source nodes in edges

### ISSUE THREAD

**Issue by dafrose** [pyrates-neuroscience/PyRates#15]
Follow-up to https://github.com/pyrates-neuroscience/PyRates/issues/14
Request by @Richert 

Suggested syntax:
```yaml
MyCircuit:
...
edges:
  -
    - [main_source: {...}, additional_source1: {...}, ...]
    - target/...
    - edge_template
    - {<attribute dict>}
```
which is identical to but clearer to read than:
```yaml
MyCircuit:
...
edges:
  - [[main_source: {...}, additional_source1: {...}, ...], target/..., edge_template, {<attribute dict>}]
```

Within the networkx representation, the main source would be the actual "source" of the edge. Additional sources would only be known from within the edge.

**Comment by dafrose** [comment]
New suggestion for the syntax: The previously introduced syntax for a **single** source node remains intact. Instead additional sources can be added via the attribute dictionary:

```yaml
MyCircuit:
...
edges:
  -
    - main_source: {source_op/source_var: edge_op/edge_var}
    - target/...
    - edge_template
    - {<attribute dict>, edge_op/edge_var: source_op/source_var}
```
