### ISSUE TITLE
Inheriting from an operator more than once causes operator key errors

### ISSUE THREAD

**Issue by Richert** [pyrates-neuroscience/PyRates#27]
I realized that there exists a bug in how operator keys are assigned, when multiple operators inherit from a common base operator:

```
base_op:
  base: OperatorTemplate
  equations:
    - "d/dt * R = -R/tau + J*I"
  variables:
    R:
      default: output
    I:
      default: input
    tau:
      default: 1.0
    J:
      default: 10.0

child_1:
  base: base_op
  variables:
    tau:
      default: 3.0

child_2
  base: base_op
  variables:
    tau:
      default: 5.0
    J:
      default: 20.0
```

 In that case, only the first operator to inherit from the base operator receives the correct key ("child_1") when used in a `CircuitTemplate`, whereas the second operator will be called "child_1" as well. 
I think that should be fixed and either all operators receive the key of the base operator, or their own.
