### ISSUE TITLE
Help with model implementation / possible feature request

### ISSUE THREAD

**Issue by jajcayn** [pyrates-neuroscience/PyRates#7]
Dear PyRates developers,

I started playing with `PyRates` today and I must say - it is very intuitive and nicely written! Kudos to you!
I started implementing a model I need to play with (thalamocortical neural mass model for simulating sleep rhythms) due to Cona et al (link [here](https://link.springer.com/article/10.1007/s10827-013-0493-1)).
Basically, it connects 6 nodes into a circuit (two thalamic and 4 cortical populations), where each node exhibit Jansen-Rit-like dynamics. I managed to create Nodes with correct Operators per each node in the model, however, I am struggling with the following:

~1. some nodes (3 of them to be precise) have external input `I_ext` - not sure how I should implement. In the paper, the base equations is~
<img width="245" alt="Screenshot 2019-09-24 at 20 25 14" src="https://user-images.githubusercontent.com/6525217/65539292-6f81fb80-df09-11e9-8ae0-ace4ac636837.png">
~and as far as I understand `PyRates` internals and Jansen-Rit example notebook the operators are taking care of `z(t)` and `y(t)`. The whole summation over the network is taken care at the circuit level, so I am not sure how to add external input. The Jansen-Rit example has external input in the potential-to-rate operator, but to be honest, I am not sure whether that is applicable here.~

~2. as seen in the equations above, some of the edges (in particular the edges between cortical and thalamic nodes) experience a delay (to be precise a delay of 1ms). Is there a possibility to include delay in the edges? If not, might this be considered a feature request?~

3. the peculiarity of the model is that self-connection of pyramidal neuron population (node) is subject to synaptic de-potentiation, i.e. when they fire at a high rate for a long time, they weaken as
<img width="292" alt="Screenshot 2019-09-24 at 20 29 10" src="https://user-images.githubusercontent.com/6525217/65539656-28483a80-df0a-11e9-8472-46f6f7293f59.png">
I am not sure how to implement this temporal dependence of weights into the model. I noticed there is an `EdgeTemplate` that takes an operator (which would include this equation), however not sure how to set it up. Is this even possible? If not, might this be considered a feature request?

~4. the thalamic populations of this model can fire in two modelities: tonacally or with bursts of action potentials. That means that their potential-to-rate operator has actually two parts:~
<img width="341" alt="Screenshot 2019-09-24 at 20 34 08" src="https://user-images.githubusercontent.com/6525217/65539945-b3293500-df0a-11e9-9785-ce3fc0b461e3.png">
~where the first summand represents bursts, while the second is responsible for tonic firing. I would need to "record" as an output both rates separately. What would you suggest as the easiest way how to achieve this? I was thinking: set up three outputs, one for bursts, one for tonic firing and one as their sum, their sum will be considered input to other nodes and the former two just record as the outputs?~

I would be very grateful for your help.
If I manage to implement the model correctly, I could contribute my code to `PyRates` docs to showcase some functionality not yet documented :)

Thanks a lot!
N.

**Comment by jajcayn** [comment]
Hey!
After digging really deep into the code, I managed to find out the solution on three out of the four problems, however, I am stuck on the de-potentiation self-connection.

I implemented it as a coupling operator:
```yaml
DisfacilitationCO:
  description: >
    Coupling operator that models disfacilitation assuming that the
    strength of pyramidal-pyramidal connections is subject to synaptic
    de-potentiation. When pyramidal cells fire at a high rate for a long time
    they weaken.
  base: CouplingOperator
  equations:
    - "V_in = c * V_out"
    - "d/dt * c = (-c + c_max * (1 - r)) / tau_c_pp"
  variables:
    c:
      description:
        Connectivity constant that reflects connection strength
        from one neural population on another.
      unit: null
      default: variable
    c_max:
      name: max_pp_connectivity
      description: "maximum connectivity constant for pyramidal-pyramidal
        connection"
      unit: null
      default: 2.22
    r:
      name: incoming_firing_rate
      description: Mean incoming firing rate at a specific synapse type
      unit: Hz
      default: input
    tau_c_pp:
      name: time_constant_pp_connectivity
      description: "time constant of synaptic disfacilitation for
        pyramidal-pyramidal connection"
      default: 10.
      unit: s
```

and attached it to the self-connection edge between Pyramidal and Pyramidal population. However, PyRates does not allow more than 1 input on the edge, hence on compiling the circuit I got following error:
```
PyRatesException: Too many input variables found. Exactly one or zero input variables are required per edge.
```
Is there any way to circumvent this? Or any ideas how else can the temporal dependence of the edge weight modelled? 
Thanks a lot!
